config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Basic config prior to API conversion 
  
  #post 'user_token' => 'user_token#create'

  root 'static_pages#home'
  #resources :users
  #get '/help',    to: 'static_pages#help'
  #get '/about',   to: 'static_pages#about'
  #get '/contact', to: 'static_pages#contact'
  get '/users/:id', to: 'users#show'

  # Config after API conversion

  scope '/api' do 
    resources :patterns
    post 'user_token' => 'user_token#create'
    get '/users/new',  to: 'users#new'
    post '/users(.:format)', to: 'users#create'
    #post 'signup' => 'users#create'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/pattern.rb
class Pattern < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

	#downcase email prior to saving to DB
	before_save { self.email = email.downcase }

	#requires name cant be blank, max length assigned
	validates :name, presence: true, length: { maximum: 64 }

	#source of email regex: https://www.railstutorial.org/book/modeling_users
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	#requires email: 
		#cant be blank
		#max length assigned
		#must be valid format
		#must be unique: true, case_sensitive: false
	validates :email, presence: true, length: { maximum: 255 },
				format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }

	#has_secure_password, provides: 
		#ability to save a securely hashed password_digest attribute to db
		#a pair of virtual attributes (password and password_confirmation), 
			#including presence validations upon object creation and a validation 
			#requiring that they match
		#An authenticate method that returns the user when the password is correct 
			#(and false otherwise)
	has_secure_password
	#password must be present, and minimum of 8 chars
	validates :password, presence: true, length: { minimum: 8 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  #original
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

  #knock config
  include Knock::Authenticable 
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :authenticate_user
  before_action :set_pattern, only: [:show, :update, :destroy]

  # GET /patterns
  # GET /patterns.json
  def index
    @patterns = Pattern.all
    render json: @patterns
  end

  # GET /patterns/1
  # GET /patterns/1.json
  def show
    @pattern = Pattern.find(params[:id])
    render json: @pattern
  end

  # GET /patterns/new
  def new
    @pattern = Pattern.new
  end

  # GET /patterns/1/edit
  def edit
  end

  # POST /patterns
  # POST /patterns.json
  def create
    @pattern = Pattern.new(pattern_params)

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Pattern was successfully created.' }
        format.json { render :show, status: :created, location: @pattern }
      else
        format.html { render :new }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patterns/1
  # PATCH/PUT /patterns/1.json
  def update
    respond_to do |format|
      if @pattern.update(pattern_params)
        format.html { redirect_to @pattern, notice: 'Pattern was successfully updated.' }
        format.json { render :show, status: :ok, location: @pattern }
      else
        format.html { render :edit }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patterns/1
  # DELETE /patterns/1.json
  def destroy
    @pattern.destroy
    respond_to do |format|
      format.html { redirect_to patterns_url, notice: 'Pattern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pattern
      @pattern = Pattern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pattern_params
      params.require(:pattern).permit(:name, :location)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/user_token_controller.rb
class UserTokenController < Knock::AuthTokenController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    respond_to do |format|
      format.json {
        if @user.save
        redirect_to :user_token => 'post', :action => 'create'
        else 
          render :json => {:errors => @user.errors.full_messages }, :status => 422
        end
      }
      format.html {
        if @user.save
          flash[:success] = "Welcome, thanks for registering!"
          redirect_to @user
        else 
          render 'new'
        end  
      }
    end
  end

  #use Strong Parameters to sanitize user input
  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password,
  									 :password_confirmation)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 
                                            'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
   <![endif]-->

</head>
<body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>

app/views/patterns/_form.html.erb
<%= form_for(@pattern) do |f| %>
  <% if @pattern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pattern.errors.count, "error") %> prohibited this pattern from being saved:</h2>

      <ul>
      <% @pattern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patterns/edit.html.erb
<h1>Editing Pattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @pattern %> |
<%= link_to 'Back', patterns_path %>

app/views/patterns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patterns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patterns.each do |pattern| %>
      <tr>
        <td><%= pattern.name %></td>
        <td><%= pattern.location %></td>
        <td><%= link_to 'Show', pattern %></td>
        <td><%= link_to 'Edit', edit_pattern_path(pattern) %></td>
        <td><%= link_to 'Destroy', pattern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pattern', new_pattern_path %>

app/views/patterns/new.html.erb
<h1>New Pattern</h1>

<%= render 'form' %>

<%= link_to 'Back', patterns_path %>

app/views/patterns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pattern.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @pattern.location %>
</p>

<%= link_to 'Edit', edit_pattern_path(@pattern) %> |
<%= link_to 'Back', patterns_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><h1>
		<%= gravatar_for @user %>
		<%= @user.name %>
	  </h1>
	</section>
  </aside>
</div>